### ISSUE TITLE
Adapt Rosetta to changes in archive node schema

### ISSUE THREAD

**Issue by kantp** [MinaFoundation/mina#52]

**Comment by Sventimir** [comment]
I'm running [rosetta-cli](https://www.rosetta-api.org/docs/rosetta_cli.html) tool in order to check whether Rosetta API behaves according to the specification. I have found some simple issues, but one that is not simple is the following:

In order to ensure transactions cannot be replayed on another network, a network identifier of sorts is being mixed into signatures. The daemon determines this identifier based on compiled-in configuration and has 2 values predefined, one for mainnet and the other for all other networks. Rosetta on the other hand does this differently, which makes the signatures it generates incompatible with the daemon. Specifically, Rosetta choses this value based on the `network_identifier`, which at the moment is configured via environment variable. We need to make sure that Rosetta choses this value in a way which is consistent with what the node does.

This is related to #39 where we want the `network_identifier` itself to be used consistently by the daemon and Rosetta. I believe this `network_identifier` cannot be compiled-in, but rather should be changeable based on runtime configuration. When this is the case, a single setting in the config file will determine the network identifierfor the node *and* for Rosetta, and also the same indetifier will be the basis for selecting the proper signature kind.

**Comment by Sventimir** [comment]
This is now in review as part of [#14041](https://github.com/MinaProtocol/mina/pull/14041).
